export const FRONT_PROJECTS_REQUEST = 'FRONT_PROJECTS_REQUEST';
export const FRONT_PROJECTS_FULLFILLED = 'FRONT_PROJECTS_FULLFILLED';
export const FRONT_PROJECTS_REJECTED = 'FRONT_PROJECTS_REJECTED';
